language: python
python:
    - "2.7"
virtualenv:
    system_site_packages: true
before_install:
    - "sudo apt-get install -qq python-lxml"
install:
    - "pip install nose pytz flask requests"
before_script:
    - python setup.py develop
script:
    - nosetests